[profile.release]
opt-level = 3

[workspace]
members = ["crates/*"]

[patch.crates-io]
# https://github.com/SoftbearStudios/bitcode/issues/2
bitcode = { git = "https://github.com/softbearstudios/bitcode" }
