[package]
name = "musli-common"
version = "0.0.44"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2021"
rust-version = "1.65"
description = """
Common utilities shared among Müsli encodings.
"""
documentation = "https://docs.rs/musli"
readme = "README.md"
homepage = "https://github.com/udoprog/musli"
repository = "https://github.com/udoprog/musli"
license = "MIT/Apache-2.0"
keywords = ["no_std", "serialization"]
categories = ["encoding"]

[features]
default = ["std"]
std = ["musli/std"]
alloc = []

[dependencies]
musli = { path = "../musli", version = "0.0.44", default-features = false }

[dev-dependencies]
rand = "0.8.5"
