[package]
name = "musli-value"
version = "0.0.34"
edition = "2021"
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/udoprog/musli"
homepage = "https://github.com/udoprog/musli"
documentation = "https://docs.rs/musli"
description = """
Buffered value support for Müsli.
"""
keywords = ["serialization", "no_std"]
categories = ["encoding"]

[features]
default = []
test = []

[dependencies]
musli = { path = "../musli", version = "0.0.34" }
musli-common = { path = "../musli-common", version = "0.0.34" }

itoa = "1.0.1"
ryu = "1.0.9"
lexical = "6.1.0"
