[package]
name = "musli-json"
version = "0.0.45"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2021"
rust-version = "1.65"
description = """
JSON support for Müsli.
"""
documentation = "https://docs.rs/musli"
readme = "README.md"
homepage = "https://github.com/udoprog/musli"
repository = "https://github.com/udoprog/musli"
license = "MIT/Apache-2.0"
keywords = ["no_std", "serialization"]
categories = ["encoding"]

[features]
default = ["std"]
std = ["musli/std", "musli-common/std", "musli-value", "alloc"]
alloc = ["musli/alloc", "musli-common/alloc", "musli-value/alloc"]
test = []

[dependencies]
musli = { path = "../musli", version = "0.0.45", default-features = false }
musli-common = { path = "../musli-common", version = "0.0.45", default-features = false }
musli-value = { path = "../musli-value", version = "0.0.45", default-features = false, optional = true }

itoa = "1.0.6"
ryu = "1.0.13"
lexical = "6.1.1"

[dev-dependencies]
rand = "0.8.5"
