[package]
name = "musli-storage"
version = "0.0.46"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2021"
rust-version = "1.66"
description = """
Partially upgrade stable format for Müsli suitable for storage.
"""
documentation = "https://docs.rs/musli"
readme = "README.md"
homepage = "https://github.com/udoprog/musli"
repository = "https://github.com/udoprog/musli"
license = "MIT/Apache-2.0"
keywords = ["no_std", "serialization"]
categories = ["encoding"]

[features]
default = ["std", "simdutf8"]
std = ["musli/std", "musli-common/std", "alloc", "simdutf8?/std"]
alloc = ["musli/alloc", "musli-common/alloc"]
test = []

[dependencies]
musli = { path = "../musli", version = "0.0.46", default-features = false }
musli-common = { path = "../musli-common", version = "0.0.46", default-features = false }
simdutf8 = { version = "0.1.4", optional = true, default-features = false }
