header = [
    "The following are the results of preliminary benchmarking and should be",
    "taken with a big grain of 🧂.",
]

url = "https://udoprog.github.io/musli/benchmarks"
branch = "gh-pages"

# features expected to be common to all.
common = ["no-rt", "std", "alloc"]

[[kinds]]
id = "dec"
description = "Decode a type"

[[kinds]]
id = "enc"
description = "Encode a type"

[[groups]]
id = "primitives"
description = "which is a small object containing one of each primitive type and a string and a byte array."

[[groups]]
id = "primpacked"
description = "Tried to achieve the same goal as `primitives`, but with a packed layout to support certain zerocopy libraries."

[[groups]]
id = "medium_enum"
description = "A moderately sized enum with many field variations."

[[groups]]
id = "large"
description = "A really big and complex struct."

[[groups]]
id = "allocated"
description = "A sparse struct which contains fairly plain allocated data like strings and vectors."

[[reports]]
id = "full"
title = "Full features"
link = "full-features"
description = [
    "These frameworks provide a fair comparison against Müsli on various areas since",
    "they support the same set of features in what types of data they can represent.",
]
features = [
    "musli-wire",
    "musli-descriptive",
    "musli-storage",
    "musli-value",
    "bincode",
    "rmp-serde",
    "postcard",
    "bitcode",
    "simdutf8",
]
expected = [
    "musli", "serde"
]

[[reports]]
id = "text"
title = "Text-based formats"
link = "text-based-formats"
description = [
    "These are text-based formats, which support the full feature set of this test suite.",
]
features = [
    "musli-json",
    "serde_json",
    "simdutf8",
]
expected = [
    "musli", "serde",
]

[[reports]]
id = "fewer"
title = "Fewer features"
link = "fewer-features"
description = [
    "This is a suite where support for 128-bit integers and maps are disabled.",
    "Usually because the underlying framework lacks support for them.",
]
features = [
    "musli-wire",
    "musli-descriptive",
    "musli-storage",
    "musli-value",
    "serde_cbor",
    # broken
    # "dlhn",
    "simdutf8",
]
expected = [
    "musli", "serde",
    "model-no-128", "model-no-map", "model-no-map-string-key"
]

[[reports]]
id = "zerocopy-rkyv"
title = "Müsli vs rkyv"
link = "müsli-vs-rkyv"
description = [
    "Comparison between [`musli-zerocopy`] and [`rkyv`].",
    "",
    "Note that `musli-zerocopy` only supports the `primitives` benchmark.",
]
features = ["musli-zerocopy", "rkyv"]
expected = [
    "model-no-cstring", "model-no-map", "model-no-map-string-key", "model-no-tuple", "model-no-usize"
]
only = ["primitives", "primpacked"]

[[reports]]
id = "zerocopy-zerocopy"
link = "müsli-vs-zerocopy"
description = [
    "Compares [`musli-zerocopy`] with [`zerocopy`].",
    "",
    "Note that `zerocopy` only supports packed primitives, so we're only comparing with that suite.",
]
title = "Müsli vs zerocopy"
features = ["musli-zerocopy", "zerocopy"]
expected = []
only = ["primpacked"]

[[reports]]
id = "bitcode-derive"
title = "Bitcode derive"
link = "bitcode-derive"
description = [
    "Uses a custom derive-based framework which does not support everything Müsli and serde does.",
]
features = [
    "musli-wire",
    "musli-descriptive",
    "musli-storage",
    "musli-value",
    "bitcode-derive",
]
expected = [
    "musli", "model-no-cstring",
]

[footnotes]
incomplete = "These formats do not support a wide range of Rust types. Exact level of support varies. But from a size perspective it makes size comparisons either unfair or simply an esoteric exercise since they can (or cannot) make stricter assumptions as a result."
i128 = "Lacks 128-bit support."

[crate_footnotes]
musli_json = ["incomplete"]
rkyv = ["incomplete"]
serde_bitcode = []
serde_cbor = ["i128"]
serde_dlhn = ["i128"]
serde_json = ["incomplete"]
derive_bitcode = []
