[package]
name = "musli"
version = "0.0.96"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2021"
rust-version = "1.76"
description = """
Müsli is a flexible and generic binary serialization framework.
"""
documentation = "https://docs.rs/musli"
readme = "README.md"
homepage = "https://github.com/udoprog/musli"
repository = "https://github.com/udoprog/musli"
license = "MIT OR Apache-2.0"
keywords = ["no-std::no-alloc", "no_std", "serialization"]
categories = ["encoding", "no-std"]

[features]
default = ["std"]
std = ["alloc"]
alloc = []

[dependencies]
musli-macros = { version = "=0.0.96", path = "../musli-macros" }
