[package]
name = "musli-zerocopy"
version = "0.0.51"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2021"
rust-version = "1.73"
description = """
Zero copy primitives for use in Müsli.
"""
documentation = "https://docs.rs/musli"
readme = "README.md"
homepage = "https://github.com/udoprog/musli"
repository = "https://github.com/udoprog/musli"
license = "MIT OR Apache-2.0"
keywords = ["no_std", "serialization"]
categories = ["encoding"]

[features]
default = ["std", "build"]
std = ["alloc"]
alloc = []
build = ["alloc"]

[dependencies]
musli-macros = { version = "=0.0.51", path = "../musli-macros" }
rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }

[dev-dependencies]
anyhow = "1.0.72"
