[package]
name = "musli-tests"
version = "0.0.0"
edition = "2021"
publish = false

[features]
default = ["std", "serde_cbor"]
std = ["musli/std", "musli-wire/std", "musli-storage/std", "musli-json/std", "rand/std", "rmp-serde", "bincode", "serde_json/std", "dlhn"]

[dependencies]
musli = { path = "../musli", default-features = false, features = ["alloc"] }
musli-wire = { path = "../musli-wire", default-features = false, features = ["alloc", "test"] }
musli-descriptive = { path = "../musli-descriptive", default-features = false, features = ["alloc", "test"] }
musli-storage = { path = "../musli-storage", default-features = false, features = ["alloc", "test"] }
musli-json = { path = "../musli-json", default-features = false, features = ["alloc", "test"] }
musli-value = { path = "../musli-value", default-features = false, features = ["alloc", "test"] }

anyhow = "1.0.70"
rand = { version = "0.8.5", default-features = false, features = ["alloc", "std_rng"] }
rmp-serde = { version = "1.1.1", optional = true }
serde = { version = "1.0.160", default-features = false, features = ["derive"] }
bincode = { version = "1.3.3", default-features = false, optional = true }
serde_json = { version = "1.0.96", default-features = false, features = ["alloc"] }
serde_cbor = { version = "0.11.2", default-features = false, features = ["alloc", "std"], optional = true }
dlhn = { version = "0.1.2", default-features = false, optional = true }

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports"] }
trybuild = "1.0.80"

[[bench]]
name = "comparison"
harness = false
