[package]
name = "musli-tests"
version = "0.0.2"
edition = "2021"
publish = false

[dev-dependencies]
musli = { path = "../musli" }
musli-wire = { path = "../musli-wire" }

anyhow = "1.0.56"
rand = "0.8.5"
rmp-serde = "1.0.0"
serde = { version = "1.0.136", features = ["derive"] }
criterion = { version = "0.3.5", features = ["html_reports"] }
bincode = "1.3.3"
serde_json = "1.0.79"

[[bench]]
name = "comparison"
harness = false
