[package]
name = "musli-tests"
version = "0.0.0"
edition = "2021"
publish = false

[features]
default = ["std"]
std = ["musli/std", "musli-wire/std", "musli-storage/std", "musli-json/std"]

[dependencies]
musli = { path = "../musli", default_features = false }
musli-wire = { path = "../musli-wire", features = ["test"], default_features = false }
musli-storage = { path = "../musli-storage", features = ["test"], default_features = false }
musli-json = { path = "../musli-json", features = ["test"], default_features = false }

anyhow = "1.0.57"
rand = "0.8.5"
rmp-serde = "1.1.0"
serde = { version = "1.0.136", features = ["derive"] }
criterion = { version = "0.3.5", features = ["html_reports"] }
bincode = "1.3.3"
serde_json = "1.0.79"
serde_cbor = "0.11.2"

trybuild = "1.0.61"

[[bench]]
name = "comparison"
harness = false
