name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: beta
        override: true
        profile: minimal
    - run: cargo build --workspace --tests --benches --examples --lib
    - run: cargo build --workspace --tests --benches --examples --lib --no-default-features

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: beta
        override: true
        profile: minimal
    - run: cargo check --tests --benches
    - run: cargo test --workspace
    - run: cargo test --workspace --no-default-features

  fuzz:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: beta
        override: true
        profile: minimal
    - run: cargo run --release --bin fuzz_test

  miri:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: beta
        override: true
        components: miri
    - run: cargo miri test

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: beta
        override: true
        profile: minimal
        components: rustfmt
    - run: cargo fmt --check
